.TH libsf 3 "stringsutil - libsf functions" "2022-04-14" "stringsutil - libsf functions"
.SH NAME
libsf \- stringsutil - libsf functions
.SH FUNCTIONS
.SS sfDelete
Free localization strings.
.PP
.nf
void sfDelete (
    strings_file_t *sf
);
.fi
.SS sfFormatString
Format a localized string.
.PP
.nf
const char * sfFormatString (
    strings_file_t *sf,
    char *buffer,
    size_t bufsize,
    const char *key,
    ...
);
.fi
.SS sfGetError
Get the last error message, if any.
.PP
.nf
const char * sfGetError (
    strings_file_t *sf
);
.fi
.SS sfGetString
Lookup a localized string.
.PP
.nf
const char * sfGetString (
    strings_file_t *sf,
    const char *key
);
.fi
.SS sfLoadFromFile
Load strings from a file.
.PP
.nf
bool  sfLoadFromFile (
    strings_file_t *sf,
    const char *filename
);
.fi
.SS sfLoadFromString
Load strings from a constant string.
.PP
.nf
bool  sfLoadFromString (
    strings_file_t *sf,
    const char *data
);
.fi
.SS sfNew
Create a new (empty) set of localization strings.
.PP
.nf
strings_file_t * sfNew (void);
.fi
.SS sfPrintf
Print a formatted localized message followed by a newline.
.PP
.nf
void sfPrintf (
    FILE *fp,
    const char *message,
    ...
);
.fi
.SS sfPuts
Print a formatted message followed by a newline.
.PP
.nf
void sfPuts (
    FILE *fp,
    const char *message
);
.fi
.SS sfRegisterDirectory
Register strings files in a directory.
.PP
.nf
void sfRegisterDirectory (
    const char *directory
);
.fi
.SS sfRegisterString
Register strings from a compiled-in string.
.PP
.nf
void sfRegisterString (
    const char *locale,
    const char *data
);
.fi
.SS sfSetLocale
Set the locale.
.PP
.nf
void sfSetLocale (void);
.fi
.SH TYPES
.SS strings_file_t
Strings file
.PP
.nf
typedef struct _strings_file_s strings_file_t;
.fi
.SH AUTHOR
.PP
Michael R Sweet
.SH COPYRIGHT
.PP
Copyright (c) 2022 by Michael R Sweet
