#!/bin/sh
#
# makesrcdist - make a source distribution of stringsutil.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating stringsutil-$version.tar.gz...
git archive --format tar --prefix=stringsutil-$version/ HEAD | gzip -v9 >stringsutil-$version.tar.gz
gpg --detach-sign stringsutil-$version.tar.gz
