name: stringsutil
base: core22
version: "1.1"
summary: Apple ".strings" file localization utility.
description: |
  StringsUtil provides a library for using Apple ".strings" localization files and
  a utility for managing those files.  It is intended as a free, smaller,
  embeddable, and more flexible alternative to GNU gettext.  Key features include:

  - Support for localizing using both Apple ".strings" and GNU gettext ".po"
    files.
  - Simple C/C++ library with support for embedding localization data in an
    executable and/or loading localizations from external files.
  - Tools for exporting, importing, and merging localization files.
  - Tool for reporting on the quality of a localization.
  - Tool for scanning C/C++ source files for localization strings.
  - Tool for doing a first pass machine translation using the LibreTranslate
    service/software.

confinement: strict

grade: stable

icon: stringsutil-128.png

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
    stringsutil:
        command: bin/stringsutil
        plugs: [home]

parts:
    main:
        plugin: autotools
        autotools-configure-parameters: [--prefix=/]
        source: .
        build-packages: [libcups2-dev, pkg-config]
        stage-packages: [libcups2]
